### ISSUE TITLE
ZAP baseline scan Docker randomly fails with `ValueError: need more than 1 value to unpack`

### ISSUE THREAD

**Issue by BookGin** [zaproxy/zaproxy#3763]
When running [the baseline scan](https://github.com/zaproxy/zaproxy/wiki/ZAP-Baseline-Scan#usage), a Python error happens **randomly**.
```
$ docker run -t owasp/zap2docker-stable zap-baseline.py -t https://www.example.com

Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Jul 18, 2017 3:42:00 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Traceback (most recent call last):
  File "/zap//zap-baseline.py", line 617, in <module>
    main(sys.argv[1:])
  File "/zap//zap-baseline.py", line 580, in main
    except IOError as (errno, strerror):
ValueError: need more than 1 value to unpack
```

Here is the information of my system:
```
Linux 3.10 x86_64 GNU/Linux
Red Hat Enterprise Linux Server 7.1 (Maipo)
Docker version 1.7.1, build 446ad9b/1.7.1
```

**Comment by thc202** [comment]
Most likely fixed in #3474. Could you try the weekly image?

**Comment by BookGin** [comment]
@thc202 Thanks for your quick response.

However, another error occurred when trying the weekly image:
```
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Jul 19, 2017 2:35:04 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
2017-07-19 02:36:59,364 I/O error(5): Failed to connect to ZAP after 120 seconds
ERROR Failed to connect to ZAP after 120 seconds
```
I cannot verify if it's fixed.

**Comment by psiinon** [comment]
@BookGin does this happen consistently?
Can you post the command you used to start the baseline scan?
We run the weekly baseline against over 100 sites every day at Mozilla and its working fine right now :)

**Comment by BookGin** [comment]
@psiinon 
For the weekly and live docker images, the timeout error happens consistently:
```
$ docker run --rm -t owasp/zap2docker-weekly zap-baseline.py -t http://mywebsite.com:8000/test.html
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Jul 19, 2017 9:40:15 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
ERROR Failed to connect to ZAP after 120 seconds
2017-07-19 09:42:10,980 I/O error(5): Failed to connect to ZAP after 120 seconds
```

For the stable image, it has approximately (13/17) 80% to fail.
```
$ docker run --rm -t owasp/zap2docker-stable zap-baseline.py -t http://mywebsite.com:8000/test.html

Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Jul 19, 2017 9:59:19 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Traceback (most recent call last):
  File "/zap//zap-baseline.py", line 617, in <module>
    main(sys.argv[1:])
  File "/zap//zap-baseline.py", line 580, in main
    except IOError as (errno, strerror):
ValueError: need more than 1 value to unpack
```

**Comment by thc202** [comment]
How much time does ZAP usually takes to launch on the machine running the Docker image?
The weekly/live images might be always failing because they have more add-ons, which increases the loading time.

Worth noting that if you are seeing the exception's message ("Failed to connect to ZAP after 120 seconds") it means this issue ("ValueError: need more than 1 value to unpack") is fixed.

**Comment by thc202** [comment]
@BookGin could you try again with the latest live image? It should now include the ZAP log (in case it's not fully starting).

**Comment by BookGin** [comment]
>How much time does ZAP usually takes to launch on the machine running the Docker image? The weekly/live images might be always failing because they have more add-ons ....

I think that's the problem, as it takes more than 2 mins to load the add-ons.

**Comment by BookGin** [comment]
@thc202 The latest live image still fails due to timeout.
```
ERROR Failed to connect to ZAP after 120 seconds
2017-07-20 01:57:35,269 I/O error(5): Failed to connect to ZAP after 120 seconds
Traceback (most recent call last):
  File "/zap//zap-baseline.py", line 285, in main
    wait_for_zap_start(zap, timeout)
  File "/zap/zap_common.py", line 194, in wait_for_zap_start
    'Failed to connect to ZAP after {0} seconds'.format(timeout))
IOError: [Errno 5] Failed to connect to ZAP after 120 seconds
```

Also, although it includes the ZAP log, I don't see any helpful information related to this issue. Here are the last 5 lines of the log.
```
...

5582 [ZAP-daemon] INFO org.parosproxy.paros.extension.ExtensionLoader  - Initializing Passive Scan Rules - beta
5582 [ZAP-daemon] INFO org.parosproxy.paros.extension.ExtensionLoader  - Initializing Easy way to replace strings in requests and responses
5586 [ZAP-daemon] INFO org.parosproxy.paros.extension.ExtensionLoader  - Initializing Tips and Tricks
5649 [ZAP-daemon] INFO org.zaproxy.zap.extension.callback.ExtensionCallback  - Started callback server on 0.0.0.0:37349
5649 [ZAP-daemon] INFO org.zaproxy.zap.extension.dynssl.ExtensionDynSSL  - Creating new root CA certificate
```

**Comment by thc202** [comment]
> Update: Or maybe it's because it cannot connect to the ZAP server?

That seems to be the problem, from the last lines of the log you provided it seems ZAP is "hanging" while generating the cert. That should not take much time, e.g.:
```
10444 [ZAP-daemon] INFO org.parosproxy.paros.extension.ExtensionLoader  - Initializing ExtensionJxBrowserLinux32
10444 [ZAP-daemon] INFO org.parosproxy.paros.extension.ExtensionLoader  - Initializing ExtSelJxBrowserLinux32
10808 [ZAP-daemon] INFO org.zaproxy.zap.extension.callback.ExtensionCallback  - Started callback server on 0.0.0.0:35570
10809 [ZAP-daemon] INFO org.zaproxy.zap.extension.dynssl.ExtensionDynSSL  - Creating new root CA certificate
11744 [ZAP-daemon] INFO org.zaproxy.zap.extension.dynssl.ExtensionDynSSL  - New root CA certificate created
11797 [ZAP-daemon] INFO org.zaproxy.zap.DaemonBootstrap  - ZAP is now listening on localhost:8080
```

**Comment by BookGin** [comment]
FYI: Not sure if it's relevant to API key #1880 or [this post](https://groups.google.com/forum/#!topic/zaproxy-users/d21tMMrmlVs). Is this issue related with API Key?

I have no idea why it's hanging when generating the root CA cert, and it even succeeds sometimes.
I'll investigate it further if I find the root cause.

@thc202 Thanks for your help 😄

**Comment by thc202** [comment]
This (the hang) should be addressed with #3864. Merging into that one.
