### ISSUE TITLE
Unnecessary decoding in Username and Password Parameters - Authentication

### ISSUE THREAD

**Issue by hecurioste** [zaproxy/zaproxy#6740]
**Describe the bug**
Login Request POST Data parameters are being decoded in the Username and Password Parameter drop down menus. This leads to being unable to successfully save your Username and Password Parameters. The Username and Password Parameters should remain encoded. 

**To Reproduce**
This may be different based on the site you are using and what the Parameters are being passed in for the Login Request POST Data

1. Open OWASP ZAP app.
2. Manual Explore
3. Enter the login url of the site you are attempting to access. 
4. Launch browser.
5. Once the browser opens, log in to the site you have access to. 
6. Once logged in, allow the page to fully load. You can now log out and close the browser. 
7. Under the Sites menu, find the site you visited. Right click and include as default context. Select OK. 
8. Now head over to History section and find the POST method of the login url. If you click on this and select Request on the dashboard above, you will be able to see the Login Request POST Data. Right click on the POST method of the login url again and select "Flag as Context" then "Default Context: Form-Based Auth Login Request.
9. Session properties should now be opened. The Login Request POST Data should now be automatically filled in. 
10. Next you'll want to choose the Username Parameter and Password Parameter. One option will be preselected. You must specify which one is which, so you must click on the dropdowns and select an option. 
11. In the dropdown options you'll notice that all the parameters from your Login Request POST Data are appearing. They will also appear decoded if any. 
12. For me, the parameters I need to choose are ones that have characters which have been decoded. If I select them and save by clicking "OK", when I reopen session properties the parameters I had chosen are no longer selected. Instead  it reverts back to one of the parameters that has no characters that needed decoding.
13. If I then select a parameter that did not have any characters that got decoded, then I can save successfully. 

Prior to a recent update, the parameter options remained encoded. Decoding these options does not allow a successful save. Ultimately, I am unable to have a Forced User log in automatically because of this. 

**Expected behavior**
Options that appear in the Username and Password Parameter dropdowns should not be decoded. The parameter options should remain in encoded form. 

**Screenshots**
Screenshot of previous "expected behavior"
![2021-08-10 at 5 58 PM](https://user-images.githubusercontent.com/24948193/128945521-4228b2ff-3feb-4c83-8ff2-3243c289f951.jpg)

Screenshot of current/new  "actual behavior"
![2021-08-10 at 6 00 PM](https://user-images.githubusercontent.com/24948193/128945643-b4c7cefe-11ea-49ef-8fce-e3a318df774c.jpg)

**Software versions**
 - ZAP: [2.10.0]

**Comment by kingthorin** [comment]
This was already discussed in the user group and has been recently addressed. 

https://github.com/zaproxy/zaproxy/pull/6720

The fix was merged 6d ago so this week’s weekly should have the fix if you care to test it.
zaproxy.org/download

**Comment by thc202** [comment]
Closing, per previous comment.

**Comment by kingthorin** [comment]
Are you using a weekly?

**Comment by hecurioste** [comment]
My apologies, I was not. I was able to figure out how to run the weekly, thanks to your link in the previous comment.

Updates after running the weekly:

- Options still appear in decoded form in the dropdown. However, this time I am able to save the decoded options. 
- If I attempt to log in with a forced user, the automatic log in fails. 

I believe the issue is that the username and password parameters are getting decoded at some point. I should be able to see and save the options in endcoded form.

**Comment by kingthorin** [comment]
What's your test process?

**Comment by kingthorin** [comment]
Per your earlier screenshots if you're not setting a logged in or logged out indicator ZAP will always try to auth, since it can't know what state yer in.

**Comment by hecurioste** [comment]
1. I start with a manual explore on Chrome. 
2. I log into `https://wmx.integration.benchprep.com/login `. 
3. I then wait for the next page to open and fully load, log out and close the window. 
4. At this point I set `https://wmx.integration.benchprep.com` as the default context. 
5. I locate the POST method for the login page in the History tab and set as Form based authentication. 
6. This opens the Session Properties window with the Authentication tab open. 
7. Here I am able to set the Username Parameter and PW parameter. The options in the dropdown appear decoded. (previously these options appeared encoded as I noted in the user group) 
8. I select the decoded options `user[email]` and `user[password]` and save. (prior to this weekly, these options saved but did not hold when reopenning the Session properties window.) 
10. I locate the GET method for the login page and Find text/html in the Response that indicates the user is logged out and set that as the log out indicator. This opens the Authentication tab again and I confirm and save.
11. I create a user and credentials under the Users tab in Sessions Property window. 
12. I select the user just created as the Forced user on the Forced User tab in Session Property window. 
13. Save and close session property window. 
14. I confirm that Forced User mode is enabled. 
15. I locate the GET method for the login page and open in browser, this should log in my forced user automatically. 
16. The login page opens, but no automatic login happens. 

Noting again that I'm following all the same steps as earlier this year where I was able to successfully log in with a Forced User. The only difference is that the options are appearing decoded which is why I believe the problem has to do with that.

**Comment by kingthorin** [comment]
At step 14, try to access a URL that would require auth.

**Comment by thc202** [comment]
The authentication messages are shown in the History tab, you can see the actual request body being sent. (The body is not en/decoded when injecting the credentials, just the tokens replaced.)

**Comment by hecurioste** [comment]
I'm taking a look at the authentication message for the POST method of the login page. I do see the correct credentials being passed in which is good, but for some reason there is still no auto login happening with the forced user.
